### ISSUE TITLE
Register single dependency

### ISSUE THREAD

**Issue by ceilfors** [laconiajs/laconia#120]
**Is your feature request related to a problem? Please describe.**
When I need to register a single dependency, the current Laconia API is asking me to return an object, which lead to a verbose code.

```js
const instances = ({ env }) => ({
  orderStream: new KinesisOrderStream(env.ORDER_STREAM_NAME)
});

exports.handler = laconia(kinesis(app))
  .register(instances);
```

**Describe the solution you'd like**
```js
exports.handler = laconia(kinesis(app))
  .register("orderStream", ({env}) => new KinesisOrderStream(env.ORDER_STREAM_NAME) );
```

This will also allow users to decouple their factories better from Laconia:

```js
exports.handler = laconia(kinesis(app))
  .register("orderStream", ({env}) => myOwnFactory(env.ORDER_STREAM_NAME) );
```

**Comment by hugosenari** [comment]
Suggestion, add helper to convert to expected type:

```javascript

const simple = (obj = {}) => deps => Object
    .entries(obj)
    .reduce((result, [key, value]) => ({ ...result, [key]: () => value(deps) }), {});

const constants = (obj = {}) => () => Object
    .entries(obj)
    .reduce((result, [key, value]) => ({ ...result, [key]: () => value }), {});
```

usage:
```javascript
laconia(app)
    .register(simple({
        orderStream: ({env}) =>  myOwnFactory(env.ORDER_STREAM_NAME)
    }))
    .register(constants(
        ONE: 1,
        foo: 'bar'
    )); 
```

**Comment by ceilfors** [comment]
That's an interesting pattern! I guess if I want to register a single dependency, we can do it like this?

```js
laconia(app)
    .register(single("orderStream", ({env}) =>  myOwnFactory(env.ORDER_STREAM_NAME)))
```

What are the pro and cons between the two approaches?

**Comment by hugosenari** [comment]
| | Adapter Pattern  | Method Overload |
| - | ------------------- | ---------------------- |
| Add feature without change core code | OK | NOK |
| Easier to test | OK | NOK |
| Less verbose | NOK | OK |
| Less imports | NOK | OK |

**Comment by ceilfors** [comment]
Thanks @hugosenari! It looks like the pro and cons can be derived into:

| | Adapter Pattern  | Method Overload |
| - | ------------------- | ---------------------- |
| Framework maintainability | OK | NOK |
| User experience | NOK | OK |

From the framework point of view, I think we should prefer user experience. On the other hand, I don't think they're mutually exclusive, if there are enough common adapter patterns in the user land, we should try to absorb it into the framework.

That said, would you be interested to make a PR for this feature?

**Comment by hugosenari** [comment]
Creates [pull request](https://github.com/laconiajs/laconia/pull/278) that add `.set(name, factory, options)` as alias for `.register(factory, options)`;

I'm not sure about naming, but this version are better than my other approach that tried to overload register. ;-)

**Comment by ceilfors** [comment]
@hugosenari I didn't realize how difficult it is to overload things in JavaScript, my bad. Maybe adding a new method is a good way to go, I'll continue the conversation in the PR.
