### ISSUE TITLE
Support binary response type 

### ISSUE THREAD

**Issue by ceilfors** [laconiajs/laconia#141]
**Is your feature request related to a problem? Please describe.**
Laconia adapter-api is not supporting binary type like Buffer or Stream.

**Describe the solution you'd like**
Application core layer must be able to return Stream or Buffer. When Stream of Buffer is received, the response content type will be set to `application/octet-stream`.

```js
const adapterApi = require("@laconia/adapter-api");

const app = () => { /* return Buffer */ }
const apigateway = adapterApi.apigateway()

exports.handler = laconia(apigateway(app)).register(instances);
```

**Additional context**

See how micro handles this: [here](https://github.com/zeit/micro/blob/069f31fa506086cdbf0ce3364d16ab972e8cc200/lib/index.js#L28)
See how aws-serverless-express handles this: [here](https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L68)
See [this thread](https://stackoverflow.com/questions/41429551/aws-api-gateway-base64decode-produces-garbled-binary/47780921#47780921) on how AWS API Gateway is handling binary type

**Comment by hugosenari** [comment]
[aws-serverless-express](https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L100) not always set content-type to `application/octet-stream` they get it from response headers when is a [response stream](https://nodejs.org/api/http.html#http_class_http_incomingmessage).

* Response stream:
  1. response.headers;
  2. application/octet-stream;

* Buffer:
  1. any suggestion ?;
  2. application/octet-stream;

**Comment by ceilfors** [comment]
Hey @hugosenari. I'm not sure if I'm getting your message correctly. I'm thinking that in our case, because the user will not be handling the response headers in the application level, it's okay for Laconia to derive the content type automatically. Otherwise, users can override the response content type with [`adapter-api`s `responseAdditionalHeaders` configuration](https://laconiajs.io/docs/api/adapter-api).

**Comment by hugosenari** [comment]
@ceilfors to convert body from stream to base64 we need a Promise/Async/Callback, but convert ApiGatewayResponse.create to async would break compatibility.

Ie:
```javascript
// static create
ApiGatewayResponse.create(output);

// static async create (everywhere should be)
await ApiGatewayResponse.create(output);
```
