### ISSUE TITLE
Document secrets manager config

### ISSUE THREAD

**Issue by ceilfors** [laconiajs/laconia#167]
Continuation of #105

Secrets manager config is currently undocumented. Modification to [laconia/website](https://github.com/laconiajs/website) is required so that users would understand how they can use this feature.

**Comment by Ankcorn** [comment]
https://github.com/laconiajs/website/pull/11

I have made an attempt to document the configuration.

**Comment by ceilfors** [comment]
This is brilliant, I've merged the code. Thank you for your contribution, @Ankcorn. Also thanks for sharing your thought at https://dev.to/ankcorn/simplify-secrets-management-with-laconiajs-4aeb. 😍 

cc @all-contributors

**Comment by ceilfors** [comment]
@all-contributors please add @Ankcorn for blog doc

**Comment by ceilfors** [comment]
This is up at https://laconiajs.io/docs/guides/retrieving-secrets
