### ISSUE TITLE
Add Event/Context Scope to Service

### ISSUE THREAD

**Issue by hugosenari** [laconiajs/laconia#217]
**Is your feature request related to a problem? Please describe.**
[Websocket Sample](https://github.com/laconiajs/examples/blob/master/examples/serverless-websocket/handler.js) would be simple if we could register `getSendHandler` inside 'event scope'. [Example](https://gist.github.com/hugosenari/35631454fd5bfa10d5eef950cc8682ac)

**Describe the solution you'd like [optional]**
Create a sub scope to register services that require event/context data to be created every for event.

**Additional context**
Some D.I frameworks let you register services inside scope:
* [Awilix Scope](https://github.com/jeffijoe/awilix#lifetime-management);
* [node-dependency-injection shared](https://github.com/zazoomauro/node-dependency-injection/wiki/Shared).

Some problems like #114 could use 'logger service' with context/event where our correlation id is connectionId or anything else from event/context.

**Comment by ceilfors** [comment]
Thanks for sharing your idea @hugosenari!

At the moment, I think this can be achieved by turning the cache off:

```js
// event object is available inside LaconiaContext 
const instances = ({ event: { requestContext: { connectionId, domainName, stage }  } }) => ({
  /* omitted */
});

const app = async ({ answer }, { send }) => {
  /* omitted */
};

// Turning cache off, so that the factory is called on every call
exports.handler = laconia(api(app)).register(instances, { cache: { enabled: false } });
```

Would this be similar with what you have in mind?

**Comment by hugosenari** [comment]
Exactly. =)
