### ISSUE TITLE
Inject SSM value while registering instances 

### ISSUE THREAD

**Issue by harry524483** [laconiajs/laconia#22]
I have followed the guide on @laconia/config but I couldn't see an option to inject mySecret while registering instances. A code snippet is as below:

`const instances = async () => ({
  userService: UserService.build(),
});`

`laconia(handler).register(instances);`

Requirement is to provide mySecret to `UserService.build()`. Currently, I am using **aws-sdk** inside UserService to get SSM value.

**Comment by ceilfors** [comment]
Thanks for reporting this issue. The `register` function's first parameter is actually `laconiaContext` object. It is briefly documented here: [register function](https://github.com/laconiajs/laconia/blob/master/packages/laconia-core/README.md#registerfactory-options).

That means, if you're trying to retrieve a secret and injecting it into UserService, you would be able to do the following:

```js
const instances = async ({ mySecret }) => ({ userService: UserService.build(mySecret) });

laconia(handler).register(instances);
```

I'll make sure that this is documented in laconia's website. Thank you!
