### ISSUE TITLE
Ease the run of manual acceptance tests

### ISSUE THREAD

**Issue by ceilfors** [laconiajs/laconia#389]
**Is your feature request related to a problem? Please describe.**
There are a couple of issues when contributors are trying to run an acceptance test by themselves:

1. SSM secret is not created automatically. The following error will occur:

```
{
"errorMessage": "Invalid parameters: /laconia-acceptrance-node8/apikey",
"errorType": "Error",
"stackTrace": [
"validateSsmData (/var/task/node_modules/@laconia/config/src/SsmConfigConverter.js:3:11)",
"SsmConfigConverter._getParameterMap (/var/task/node_modules/@laconia/config/src/SsmConfigConverter.js:19:5)",
"<anonymous>",
"process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:228:7)"
]
}
```

2. S3 buckets has a name conflict. The following error will occur:

```
An error occurred: S3Tracker - laconia-acceptance-node8-tracker already exists.
```

**Describe the solution you'd like**
- Contributors should be able to run acceptance test to their own AWS account with one command
- And/or, the steps to run the acceptance test must be documented well

**Additional context**
- This issue is reported by @hugosenari via gitter.
- Related to #104

**Comment by ceilfors** [comment]
SecureString is not something that we can create automatically. But someone in StackOverflow suggested that we can use [Custom Resource](https://stackoverflow.com/a/52305236/2464295)

**Comment by hugosenari** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules
>  Bucket names must be unique across all existing bucket names in Amazon S3.

This mean that S3 bucket name must contain accountId.

**Comment by hugosenari** [comment]
#432 and #435 fix this issue

**Comment by ceilfors** [comment]
🎉
