### ISSUE TITLE
APIGateway Websocket support

### ISSUE THREAD

**Issue by Strernd** [laconiajs/laconia#41]
There seems to be no support for websocket calls with the current API-Gatewat Adapter

Handler and serverless.yml: https://gist.github.com/Strernd/ead6308cec5b1ef557ce45995c676ed4

`https://xxx.execute-api.eu-central-1.amazonaws.com/dev/laconia?hello=world`
returns
```
{
  "body": null,
  "hello": "world"
}
```

`> wscat -c wss://xxx.execute-api.eu-central-1.amazonaws.com/dev`
`> {action: "laconia"}`
returns 
```
< {"message": "Internal server error", "connectionId":"Zq0lpfIyliACGbQ=", "requestId":"Zq1LaGLQliAFsbA="}
```

I will try to look into the problem and to make a PR, but currently I'm a bit lost on how to do it.

**Comment by ceilfors** [comment]
Thank you for raising this issue @Strernd. Do bear with me as I'm new to API Gateway websocket capability.

As far as I can see, the error is thrown because the event structure of websocket is different from HTTP, it can't be parsed the same way. The response structure seems to be similar with HTTP, but I can't find the official documentation that outline the response format.

In term of the PR, first we will have to brainstorm the design the API from Laconia perspective first. There are multiple levels of design in this context:
- Manual adapter creation: We can help on the event parsing. What's the most common event body format here for websocket?
- Built-in Adapter: What's the most common "port" here?
- Sending message back to devices: Same questions above.

As you have the need of websocket, you'll be able to help determine what you'll find helpful from a framework. Maybe you can share your use case, and we can drive the design from there. I'm happy to help if you'd like to pursue this.

On using it now, you should be able to do it this way.
```
const laconia = require("@laconia/core");
const { res } = require("@laconia/event").apigateway;

const app = async event => {
  console.log("Incoming request", event);
  return "success";
};

const adapter = app => async event => {
  try {
    const output = await app(event);
    return res(output);
  } catch (err) {
    return res(err.message, 500);
  }
};

exports.handler = laconia(adapter(app));
```

To retain context, I'm also adding more information to this ticket:

<details> 
  <summary>Error log in Lambda</summary><p>

```
{
    "errorMessage": "Cannot read property 'Content-Type' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "module.exports.event (/var/task/node_modules/@laconia/adapter-api/node_modules/@laconia/event/src/apigateway/parseRequestBody.js:17:36)",
        "fromRaw (/var/task/node_modules/@laconia/adapter-api/node_modules/@laconia/event/src/apigateway/ApiGatewayEvent.js:10:49)",
        "ApiGatewayParamsInputConverter.convert (/var/task/node_modules/@laconia/adapter-api/src/ApiGatewayParamsInputConverter.js:5:29)",
        "ApiGatewayEventAdapter.handle (/var/task/node_modules/@laconia/adapter-api/src/ApiGatewayEventAdapter.js:17:45)",
        "laconia (/var/task/node_modules/@laconia/core/src/laconia.js:30:28)",
        "<anonymous>"
    ]
}
```
</p></details>

<details> 
  <summary>$connect Request format</summary><p>

```
{
    "headers": {
        "Host": "1jo5thqox7.execute-api.eu-west-1.amazonaws.com",
        "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
        "Sec-WebSocket-Key": "FPRIeEeYpG/0JRmRwHq4mw==",
        "Sec-WebSocket-Version": "13",
        "X-Amzn-Trace-Id": "Root=1-5cdb99af-e47b3f3922f8242b7e0c6619",
        "X-Forwarded-For": "81.100.203.243",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https"
    },
    "multiValueHeaders": {
        "Host": [
            "1jo5thqox7.execute-api.eu-west-1.amazonaws.com"
        ],
        "Sec-WebSocket-Extensions": [
            "permessage-deflate; client_max_window_bits"
        ],
        "Sec-WebSocket-Key": [
            "FPRIeEeYpG/0JRmRwHq4mw=="
        ],
        "Sec-WebSocket-Version": [
            "13"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-5cdb99af-e47b3f3922f8242b7e0c6619"
        ],
        "X-Forwarded-For": [
            "81.100.203.243"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ]
    },
    "requestContext": {
        "routeKey": "$connect",
        "messageId": null,
        "eventType": "CONNECT",
        "extendedRequestId": "ZtTzbHYgjoEFjFw=",
        "requestTime": "15/May/2019:04:46:39 +0000",
        "messageDirection": "IN",
        "stage": "node8",
        "connectedAt": 1557895599503,
        "requestTimeEpoch": 1557895599504,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "81.100.203.243",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "ZtTzbHYgjoEFjFw=",
        "domainName": "1jo5thqox7.execute-api.eu-west-1.amazonaws.com",
        "connectionId": "ZtTzbeYEDoECHAg=",
        "apiId": "1jo5thqox7"
    },
    "isBase64Encoded": false
}
```
</p></details>

<details> 
  <summary>$disconnect Request format</summary><p>

```
{
    "headers": {
        "Host": "1jo5thqox7.execute-api.eu-west-1.amazonaws.com",
        "x-api-key": "",
        "x-restapi": ""
    },
    "multiValueHeaders": {
        "Host": [
            "1jo5thqox7.execute-api.eu-west-1.amazonaws.com"
        ],
        "x-api-key": [
            ""
        ],
        "x-restapi": [
            ""
        ]
    },
    "requestContext": {
        "routeKey": "$disconnect",
        "messageId": null,
        "eventType": "DISCONNECT",
        "extendedRequestId": "ZtUPkHCTjoEFkzQ=",
        "requestTime": "15/May/2019:04:49:39 +0000",
        "messageDirection": "IN",
        "stage": "node8",
        "connectedAt": 1557895599503,
        "requestTimeEpoch": 1557895779622,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "81.100.203.243",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "ZtUPkHCTjoEFkzQ=",
        "domainName": "1jo5thqox7.execute-api.eu-west-1.amazonaws.com",
        "connectionId": "ZtTzbeYEDoECHAg=",
        "apiId": "1jo5thqox7"
    },
    "isBase64Encoded": false
}
```
</p></details>

<details> 
  <summary>$default Request format</summary></p>

```
{
    "requestContext": {
        "routeKey": "$default",
        "messageId": "ZtTz_eYbjoECHAg=",
        "eventType": "MESSAGE",
        "extendedRequestId": "ZtTz_E5DDoEFinQ=",
        "requestTime": "15/May/2019:04:46:43 +0000",
        "messageDirection": "IN",
        "stage": "node8",
        "connectedAt": 1557895599503,
        "requestTimeEpoch": 1557895603144,
        "identity": {
            "cognitoIdentityPoolId": null,
            "cognitoIdentityId": null,
            "principalOrgId": null,
            "cognitoAuthenticationType": null,
            "userArn": null,
            "userAgent": null,
            "accountId": null,
            "caller": null,
            "sourceIp": "81.100.203.243",
            "accessKey": null,
            "cognitoAuthenticationProvider": null,
            "user": null
        },
        "requestId": "ZtTz_E5DDoEFinQ=",
        "domainName": "1jo5thqox7.execute-api.eu-west-1.amazonaws.com",
        "connectionId": "ZtTzbeYEDoECHAg=",
        "apiId": "1jo5thqox7"
    },
    "body": "hello",
    "isBase64Encoded": false
}
```
</p></details>

**Comment by Strernd** [comment]
I tried the code for the handler and it worked. 

Four our use-case it would be sufficient to have JSON parsing for the body, the most common port for our use-case is the websocket event via apigateway, if this is what you mean.
Sending back messages shouldn't be handled in the out adapter, because it's not request/response. It's sufficient to return anything, if I understood AWS correctly. 
Message sending to the client would work via the AWS.ApiGatewayManagementApi , so I would include this as a dependency and do it in the handler.
Thanks for your help so far!

**Comment by ceilfors** [comment]
Cool. If JSON is a common use case, I guess we can support websocket parsing in Laconia like the below code example. Let me know if there's anything I can help on creating PR, I definitely welcome your contribution :)

**`@laconia/event`:**

```
const laconia = require("@laconia/core");
const { parseWebsocket } = require("@laconia/event").apigateway;

const app = async webmessage => {
  console.log("Incoming request", message);
  return "success";
};

const adapter = app => async event => {
  try {
    const output = await app(parseWebsocket(event));
    return res(output);
  } catch (err) {
    return res(err.message, 500);
  }
};

exports.handler = laconia(adapter(app));
```

**`@laconia/adapter-api`:**

```
const laconia = require("@laconia/core");

// Basically this is the adapter code above
// Automatically parse JSON
// Automatically return 200, and 500 on error
// Do you have any other statusCode on error? Would you customise statusCode in your webSocket implementation?
const websocket = require("@laconia/adapter-api").websocket();

const app = async webmessage => {
  console.log("Incoming request", message);
  return "success";
};

exports.handler = laconia(websocket(app));
```

**Sending message**

I guess the use case I'm interested to know is, what do you do when you get the message from websocket? Do you store it in DynamoDB? Are you replying to the client directly on every message? I think there are interesting use case where a framework can help speed the development up.

**Comment by Strernd** [comment]
Thanks, I will take a look into the implementation. I think I've got enough understand how laconia works here. 
I think the use case we will have is, that we will store the connectionId into Redis with a handler that listens to the $connection event. The connection will be referenced to a userId, that we know from authentication. A user could open many browser tabs, and we would have to send something to every tab (multiple connection Ids). 
It could be that we reply directly to a message, but then, again, just answering to the connectionId the message came from might not suffice.

**Comment by ceilfors** [comment]
Cool! My suggestion would be to start with what you'll find useful in your project, whether that's the `@laconia/event` or `@laconia/adapter-api`. I have also just completed the [CONTRIBUTING](https://github.com/laconiajs/laconia/blob/master/CONTRIBUTING.md) document, which you might find helpful to read. Do reach out if you need help on the PR.

Thanks for explanation the use case! I was thinking that there's an opportunity to implement an even higher level use of framework via DynamoDB if you're interested. Something like the below (pure raw thought).

** On connect / disconnect **
```
const { websocketHandler } = require('@laconia/websocket')

// Understands event type of $connect and $disconnect, automatically store and delete connection ID in DynamoDB
exports.handler = websocketHandler(process.env.WEBSOCKET_CONNECTION_TABLE_NAME)
```

** On sending message **
```
const { createWss } = require("@laconia/websocket");

// wss object is injected
const app = async (event, { wss }) => {
  // Automatically get all client objects from DynamoDB
  const clients = await wss.getClients()

  // Sends data to a client, wraps apigwManagementApi
  await clients[0].send("something")

  // Broadcast, also wraps apigwManagementApi
  await Promise.all(clients.map(c => c.send('something')))
  await wss.broadcast('something')
};

exports.handler = laconia(app).register(createWss(process.env.WEBSOCKET_CONNECTION_TABLE_NAME));
```

**Comment by Strernd** [comment]
Sounds like a great interface to me.

**Comment by ceilfors** [comment]
@laconiajs/core-contributors Would you mind having a look into the API design above? I have not used WebSocket in anger in AWS nor anywhere else.

**Comment by ceilfors** [comment]
@Strernd I have now merged your PR. The only thing left would be the API reference documentation. Would you be interested to update the documentation at [laconia/website](https://github.com/laconiajs/website)?

**Comment by Strernd** [comment]
@ceilfors I think I can't make the time for it now, sorry.

**Comment by ceilfors** [comment]
@Strernd That's ok! I was just splitting the issue out to another ticket.
