### ISSUE TITLE
Node 8 EOL

### ISSUE THREAD

**Issue by hugosenari** [laconiajs/laconia#419]
**Describe the bug**

Node 8 are reaching EOL, [AWS will deprecate it](https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html)

**Expected behavior**
Acceptance Tests and Circleci shouldn't run Node 8 anymore

**Additional context**
We should add another bug to add [support to Node 12](https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/)

**Comment by hugosenari** [comment]
We could also look for code improvements with new ES features available at Node 10.
Ie:
- Object rest/spread properties: is available at Node 8 but not well 'spreaded' :-D
- Promise.prototype.finally;
- async iterators/generators;
- Function.prototype.toString;
- String.prototype.trimStart() and String.prototype.trimEnd();
- Array.prototype.values;

**Comment by ceilfors** [comment]
Thanks @hugosenari for raising this. Related to this issue, lately, I've been wondering if laconia should have been written in TypeScript, I realise that many of our users are actually writing their applications in TypeScript (I might live in a bubble).

In #35, I thought JavaScript will help on community inclusivity, I might turn out to be wrong, because if our users are using TS, they might prefer laconia to be in TS.

What are your thoughts around TS? @hugosenari @geoffdutton @sakthivel-tw

**Comment by geoffdutton** [comment]
> What are your thoughts around TS? @hugosenari @geoffdutton @sakthivel-tw

I don't have much experience with TS, so I don't have a strong opinion one way or the other. What's the advantage of it being written in TypeScript vs just having the Type definitions?

**Comment by hugosenari** [comment]
> I might turn out to be wrong, because if our users are using TS

Data about this (last 12 months, around the world, web search):

![image](https://user-images.githubusercontent.com/863299/69576213-9c569b80-0faa-11ea-8a8e-76dacd623ae4.png)
![image](https://user-images.githubusercontent.com/863299/69576268-b3958900-0faa-11ea-9d7a-a415926ac52e.png)
![image](https://user-images.githubusercontent.com/863299/69576331-d0ca5780-0faa-11ea-9492-c971a303fc69.png)

Note: These aren't data about our users, so this don't mean your user aren't typescript lovers.

**Comment by ceilfors** [comment]
@geoffdutton Thanks for the input, and good question. During my analysis, one of the reasons I keep is as JavaScript is because it will be more welcoming for our users to contribute back. But I'm noticing that there are more TS than JS users - But then again I might live in a bubble here.

@hugosenari That's an interesting data! What about you, are you using `laconia` with JS or TS? Forgive me to deviate the thread. It just popped in my mind because you listed down the new ES features.

**Comment by sakthivel-tw** [comment]
I have little experience with TS and so I don't have any suggestions. I have heard people say TS is pragmatic. Never had a chance to try TS, apart from experiments.

**Comment by hugosenari** [comment]
@ceilfors Here is my biassed/opinionated thoughts about JS x TS, ignore it and stay with data :wink: 

As laconia user:
- All we need are d.ts files.
- Maybe a [flow libdef](https://flow.org/en/docs/libdefs/) too.
- Being 'JS first', was one of reasons why I choose laconia.
- All I need was a [JS DI Framework](https://gist.github.com/hugosenari/ccde51409ae7bbd111f2cd0a39ba778a) (TS has more options).
- Most of possible laconia users prefer Nest (TS) or Express (JS).
- They are not the right tool for the job, but they got the work done.

As laconia dev:
- Any TS dev could help with JS code, and is not too hard for a JS dev contribute to TS code.
- TS increases verbosity to gain some features, but most of them are coming for next JS iteration.
- We could use babel if these features matters.
- Our current coupling with TS is weak, and [this is good](http://technosophos.com/2018/08/19/the-true-hardest-problem-is-tight-vs-weak-coupling.html). 

As code addicted:
- In the end, TS is just JS with ['type hints'](https://www.python.org/dev/peps/pep-0484/#abstract).
- [TS Method Overload](https://howtodoinjava.com/typescript/function-overloading/) freaks me out.
- JS is the [boring tech](http://boringtechnology.club/).
- Maybe language doesn't matter more than [other changes](https://dev.to/vaibsgharge/imperative-vs-declarative-programming-your-enemy-is-not-object-oriented-programming-52fe)

As dev worker:
- At job my team and I don't know TS.
- Other team uses Angular/TS with `any` everywhere (I know isn't TS fault).

My bubble (friends) about TS:
- "It's for Java dev that don't know how to live without classes" (I'm Java dev too :laughing:).

My opinions about transpilation over the time:
1. "Blergh, in the end will be JS", (because I don't want to learn CoffeScript).
2. "Minimal, transpilation is OK", (because we need support IE 6).
3. "Anything nowadays are transpiled", (because of our webpacked build).

**Comment by ceilfors** [comment]
@sakthivel-tw Thanks for the input!

@hugosenari Thanks for such a thoughtful and thorough comment. I think you have hit the nail on the head with:

> Any TS dev could help with JS code, and is not too hard for a JS dev contribute to TS code.

It's funny when you mentioned:

> "It's for Java dev that don't know how to live without classes" 

If you haven't noticed, I started my career with Java, and classes are all over the place in laconia code base :)

Thanks all for the feedback, I think that's quite a strong input to keep the project in JavaScript for inclusivity.

**Comment by hugosenari** [comment]
TODO:
- [X] Update serverless.yml (done #GH-419)
- [X] Update package.json (done #GH-419)
- [ ] Update circleci/config.yml
- [ ] Update examples

**Comment by geoffdutton** [comment]
Another TODO:
- [ ]  Update `.nvmrc` -- probably with 10?

**Comment by hugosenari** [comment]
Closing this in favor of 10 deprecation #747
