### ISSUE TITLE
Number 'protocol' for laconia-config

### ISSUE THREAD

**Issue by hugosenari** [laconiajs/laconia#542]
**Is your feature request related to a problem? Please describe.**
AWS Lambda API states that [all config should be strings](https://github.com/serverless/serverless/pull/4890).

This means that all our config should be string and then converted to number.

**Describe the solution you'd like [optional]**
- Add `LACONIA_CONFIG_PORT: integer:8080` to env to be intepreted by laconia-config as `parseInt(8080)`;
- Add `LACONIA_CONFIG_TAX: float:80.80` to env to be interpreted by laconia-config as `parseFloat(80.08)`;
- Update documentation and examples with new features.

**Comment by geoffdutton** [comment]
@hugosenari I can implement this, I haven't contributed in awhile. Or are you working on it?

**Comment by ceilfors** [comment]
Thanks @hugosenari and @geoffdutton! This is now released under 1.10.0. And the docs is live at https://laconiajs.io/docs/api/config.

**Comment by ceilfors** [comment]
@all-contributors please add @geoffdutton for code

**Comment by ceilfors** [comment]
@all-contributors please add @hugosenari for maintenance
