### ISSUE TITLE
Dependabot doesn't seem to be working

### ISSUE THREAD

**Issue by geoffdutton** [laconiajs/laconia#639]
**Describe the bug**
The last @dependabot was [Aug 1](https://github.com/laconiajs/laconia/pull/635). I know at the very least jest has a newer patch version.

**Expected behavior**
Dependabot continues to open PRs for packages upgrades.

**Additional context**
I know GitHub has been trying to more tightly integrate Dependabot, that might part of the issue. Otherwise, maybe some credentials got reset or permissions revoked.

Edit: @ceilfors Did you change the frequency to monthly?

**Comment by ceilfors** [comment]
_Apologies for my slow reply, for some reason GitHub has no longer send a notification to my email! Still figuring out how to fix this_

I can see that the latest merge from dependabot is on 1 Oct, so I'm closing this issue: https://github.com/laconiajs/laconia/pull/671
