### ISSUE TITLE
Node 14 Support

### ISSUE THREAD

**Issue by hugosenari** [laconiajs/laconia#657]
**Is your feature request related to a problem? Please describe.**
Add support to Node 14.

**Describe the solution you'd like [optional]**
Our unit tests should run with Node 14.

**Additional context**
Node 14 will be [LTS in 2020-10](https://github.com/nodejs/release#release-schedule), since we can't run acceptance tests before AWS offers it, we could at least configure unit tests.

[What is new](https://node.green/#ES2020)

**TODO:**
- [ ] Update CI to run unit tests with Node 14
- [ ] Wait AWS and configure Acceptance Tests with Node 14

**Comment by geoffdutton** [comment]
Agreed, I was going to suggest we just add it to the CI and perhaps update the root `.nvmrc`.

**Comment by hugosenari** [comment]
Update: Node.js 14.x runtime now available in AWS Lambda
https://aws.amazon.com/blogs/compute/node-js-14-x-runtime-now-available-in-aws-lambda/

**Comment by hugosenari** [comment]
We are talking about Node 20 now :-D
