### ISSUE TITLE
adapter-api does not support headers inputType

### ISSUE THREAD

**Issue by kirbyjs** [laconiajs/laconia#812]
### Description

The `@laconia/adapter-api` package does not support the `headers` `inputType` from the [ApiGatewayEvent](https://laconiajs.io/docs/api/event#apigatewayreqevent).

**Is your feature request related to a problem? Please describe.**
No, there is a work around with the `@laconia/event` package.

**Describe the solution you'd like [optional]**
It would also be nice to provide the whole `ApiGatewayEvent` instead of just a specific `inputType` or at least a way to receive `headers`.

**Additional context**
Scanning through #124 they seem partially related.

**Comment by ceilfors** [comment]
@all-contributors please add @kirbyjs for ideas

**Comment by ceilfors** [comment]
Thanks for raising this issue @kirbyjs!

The `adapter-api` does support headers input, which currently is undocumented (feel free to raise a pull request :) ):
- See the parameter `includeInputHeader` setting here: https://github.com/laconiajs/laconia/blob/4bcb1161e4fde1b44e7a5258883c3d734a169a4f/packages/laconia-adapter-api/src/createApiGatewayAdapter.js
- Your `app` function will be called with headers, like this: https://github.com/laconiajs/laconia/blob/master/packages/laconia-adapter-api/test/ApiGatewayEventAdapter.spec.js#L60

**Comment by kirbyjs** [comment]
> Your app function will be called with headers, like this: master/packages/laconia-adapter-api/test/ApiGatewayEventAdapter.spec.js#L60

I noticed this option the other day which was pretty slick! Also didn't know about the `includeInputHeader`! 👍🏼  That's good to know and might look into adding that into the docs! I have an incoming PR that I've been working on to improve upon the current types.

I still think it might be a good idea to just allow providing the full `APIGatewayEvent` to future proof the adapter. But it seems that from you comment that everything is currently supported, so feel free to close this issue 😃

**Comment by ceilfors** [comment]
That's great! I'll close this issue :)
