### ISSUE TITLE
Be Able to Dynamically Set Api Gateway Status Code

### ISSUE THREAD

**Issue by kirbyjs** [laconiajs/laconia#817]
**Is your feature request related to a problem? Please describe.**
Yes, currently the api gateway handler has no way of dynamically setting the status code of the response. Currently we are only able to set it to one value through the [api gateway adapter config](https://github.com/laconiajs/laconia/blob/master/packages/laconia-adapter-api/src/createApiGatewayAdapter.js#L20).

**Describe the solution you'd like [optional]**
Probably would be best to implement something along the lines of the [errorMappings](https://github.com/laconiajs/laconia/blob/master/packages/laconia-adapter-api/src/ApiGatewayNameMappingErrorConverter.js). I'm thinking something along the lines of a `responseMapper` that is a function and accepts a `statusCode` and `body` response like errorMappings does. 

_or_

I think I like this option a little better is adding a `status` (or `statusCode`) function that accepts a new status that is passed through the [laconia context in the handler](https://github.com/laconiajs/laconia/blob/master/packages/laconia-adapter-api/src/ApiGatewayEventAdapter.js#L16). 

so the code would be something like:

```js
// in the ApiGatewayOutputConverter
status(statusCode: number) {
  this.statusCode = statusCode;
}

// in the ApiGatewayEventAdapter
laconiaContext.status = this.outputConverter.status.bind(this);

// in the consumers handler
laconiaContext.status(204);
return '';
```

we could also name that function whatever if we wanted to be extra careful not introducing a breaking change and overwriting something in the laconiaContext. We could also just pass that function as another argument. 🤷🏼‍♂️ 

**Additional context**

**Comment by ceilfors** [comment]
@kirbyjs Thanks for raising this! Can you describe the scenario in which you return a different status code in a single Lambda? I guess I'm wondering if this is a behaviour that I'd like the framework to support.

**Comment by ceilfors** [comment]
Closed due to inactivity
